#!/bin/sh

cp $1/Image/parameter.txt $1/parameter
BOOTLOADER=$(awk '$1=="bootloader" {print $2}' $1/package-file)
BOOTLOADER=$(echo $BOOTLOADER | tr -d '\r')

afptool -pack $1 $2.tmp

img_maker -rk33 $1/$BOOTLOADER $2.tmp $2

rm -rf $2.tmp
